micronaut:
  application:
    name: auction5
  security:
    authentication: idtoken
    oauth2:
      clients:
        google:
          client-id: 815821376525-tg39nstqsl4gutefm2nv4dm6rfquuik7.apps.googleusercontent.com
          client-secret: not-the-real-secret
          openid:
            issuer: https://accounts.google.com
    endpoints:
      logout:
        get-allowed: true
datasources:
  default:
    driverClassName: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
    url: jdbc:mysql://localhost:3306
    username: auction
    password: robinworm
#  h2:
#    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password: ''
#    driverClassName: org.h2.Driver
#    schema-generate: CREATE_DROP
#    dialect: H2
